### ISSUE TITLE
Enhancement : Preventing Curses and Status cards from being upgraded

### ISSUE THREAD

**Issue by PABessero** [Moocowsgomoo/StS-ConstructMod#11]
Hey there, a quick idea i had (while doing stupid things again), the game prevents you from choosing a curse or a status card while using an unupgraded Armaments, would it be possible to do the same while using Stasis?

**Comment by Moocowsgomoo** [comment]
This one's actually intentional, as you can use Stasis as a one-time Exhaust effect to get rid of a curse, etc.
It's not always ideal, but I think it's probably better to allow it than disallow it.

**Comment by KongMD-Steam** [comment]
Agreed. Burning 1 energy to kill a troublesome curse can be quite useful.
