### ISSUE TITLE
Game-crashing Core and Awakened One Form transition interaction

### ISSUE THREAD

**Issue by Glaargh** [Moocowsgomoo/StS-ConstructMod#14]
The game crashes if the Awakened One is targeted while it is awakening: I am unsure whether it was the Cores themselves hitting it and causing the crash or Autoturret.

**Comment by Moocowsgomoo** [comment]
Make sure you're on [Construct version 0.6.8](https://github.com/Moocowsgomoo/StS-ConstructMod/releases) or higher - that fixes a crash between Flame Core and Awakened One. I can't replicate a crash in the current version, so if it still occurs for you definitely let me know. Thanks!
