### ISSUE TITLE
Unable to choose alternate relic, I have leveled up 3 times,  but still haven't unlocked the config

### ISSUE THREAD

**Issue by Haithere23** [Moocowsgomoo/StS-ConstructMod#15]

**Comment by Moocowsgomoo** [comment]
To find the config menu, click "Mods" on the main menu, then "The Construct" in the box to the left, then "Config" just below that box.

Have you reached the config menu, and it still displays "Reach EXP Level 1 as the Construct to unlock"?

**Comment by Haithere23** [comment]
I reinstalled and it fixed itself.
