### ISSUE TITLE
Synchronize doesn't draw cards

### ISSUE THREAD

**Issue by ClassixX** [Moocowsgomoo/StS-ConstructMod#16]
As the title states, the card "Synchronize" doesn't draw cards when the effect activates. I have tried all versions of the card (normal, upgraded, mega-upgraded), the effect simply doesn't work correctly.

**Comment by Moocowsgomoo** [comment]
Synchronize was changed to not draw cards anymore as of version 0.7.1, as it was a bit too powerful. Sorry about that!

**Comment by ClassixX** [comment]
Then the buff text needs to be updated, if that hasnt been done in the past day or so.
