### ISSUE TITLE
"Master Core" Relic

### ISSUE THREAD

**Issue by EverynameTaken** [Moocowsgomoo/StS-ConstructMod#17]
I don't know is this bug fix but every times get this relic game crash on next fight even relog it still crash at start of the combat

**Comment by Moocowsgomoo** [comment]
Make sure you're on [version 0.6.6 or higher](https://github.com/Moocowsgomoo/StS-ConstructMod/releases) - Master Core had a chance to crash the game before that.
I can't seem to replicate the crash on the current version. If it happens again, would you mind posting the error log? Thanks!
