### ISSUE TITLE
If you have clockwork Chicken it can be upgraded again in combat resulting into scrambled Egg without changing art

### ISSUE THREAD

**Issue by AlexTalavari** [Moocowsgomoo/StS-ConstructMod#18]
You can see an example here 
[Youtube video](https://youtu.be/9TUzx7bl-eA?t=59m49s
)

This can be fixed by changing line 182 at [ClockworkEgg.java]( https://github.com/Moocowsgomoo/StS-ConstructMod/blob/master/src/main/java/constructmod/cards/ClockworkEgg.java)

to 
`if (inCombat and this.timesUpgraded >3) this.isScrambled = true;`

**Comment by Moocowsgomoo** [comment]
Fixed in version 0.7.3. Thanks for the detailed report!
