### ISSUE TITLE
Wedding Ring doesn't work in opening hand after being used then save and resume

### ISSUE THREAD

**Issue by SilentJ28** [Moocowsgomoo/StS-ConstructMod#20]
Was playing the witch class mod at the time but had construct enabled and got the wedding ring relic. I linked Plague spreader+ and Metamorphisis. Both cards were in my opening hand.
Played plague spreader which played metamorphis. Saved and quit and tried playing metamorphisis first and wedding ring didn't trigger. Saved and quit and tried plague spreader again and it still didn't trigger.

Is the once per turn on wedding ring being remembered for the current turn through save and quit?

This was the first save and quit since getting the relic so unsure if that alone broke it.

**Comment by SilentJ28** [comment]
Next fight wedding ring also didn't trigger when both were in opening hand. Seems to just be broken in general after the save and quit

**Comment by Moocowsgomoo** [comment]
Another casualty of the ID changes - fixed as of [version 0.9.2](https://github.com/Moocowsgomoo/StS-ConstructMod/releases). Thanks for the report!
