### ISSUE TITLE
Synchronize Always Deals Damage On Draw

### ISSUE THREAD

**Issue by imakunee** [Moocowsgomoo/StS-ConstructMod#23]
Every time a card is drawn, Synchronize will deal damage to all enemies regardless of whether or not the drawn card is the same as the previous. 

Versions according to ModTheSpire:
ModTheSpire 3.2.0
BaseMod 3.5.0
TheConstruct 0.9.6

**Comment by Moocowsgomoo** [comment]
Fixed as of [version 0.9.7](https://github.com/Moocowsgomoo/StS-ConstructMod/releases), along with (hopefully) all other Synchronize bugs. Thanks for the report!
