### ISSUE TITLE
Custom Mode menu displays The Construct as The Ironclad

### ISSUE THREAD

**Issue by RandomlyAwesome** [Moocowsgomoo/StS-ConstructMod#24]
The character selection icons in the custom mode menu have a second copy of the icon for the ironclad(with the ironclad's mouseover text) instead of the construct's.
Selecting the duplicate ironclad does start the game as the construct without any noticable problems so it seems to only be visual.

**Comment by Moocowsgomoo** [comment]
Fixed in the [latest version.](https://github.com/Moocowsgomoo/StS-ConstructMod/releases) Thanks for the report!
