### ISSUE TITLE
Challenge mode conflicting with InfiniteSpire

### ISSUE THREAD

**Issue by ClassixX** [Moocowsgomoo/StS-ConstructMod#27]
InfiniteSpire has an event that randomizes a characters starter relics.
This allows for any character to randomly get any challenges restrictions put upon them.
Is it be possible not to implement the Challenge mods in the form of starter relics, so that this conflict could be evaded?

**Comment by Moocowsgomoo** [comment]
Fixed as of the [latest version](https://github.com/Moocowsgomoo/StS-ConstructMod/releases). Thanks for the report!
