### ISSUE TITLE
CharScreenSelectFXPatch not working

### ISSUE THREAD

**Issue by fiiiiilth** [Moocowsgomoo/StS-ConstructMod#4]
Seems like the rloc for the insert patch needs adjusting now, 64 seems to have done the trick.

As a side note, since I'm bad at making patches, I'm going to borrow this one for FruityMod if that's cool with you.

Either way, glad to see Construct updated!

**Comment by Moocowsgomoo** [comment]
I set it to 37 while testing independently, and that also seems to work. My method is to literally just enter random numbers and make sure it doesn't crash the game lol.
Absolutely, it was meant to be taken & used by other character modders. Ascension mode support is like my #1 request for other custom characters :D
