### ISSUE TITLE
Critical Hit Cycles with a weak enemy

### ISSUE THREAD

**Issue by KongMD-Steam** [Moocowsgomoo/StS-ConstructMod#7]
## Expected Behavior
The Critical Hit card stays in hand, when drawn with a Weakened enemy.

## Actual Behavior
The card cycles to the discard pile. The card will not cycle if there is a Vulnerable enemy.

## Steps to Reproduce the Problem
https://gfycat.com/OrnateWhichDouglasfirbarkbeetle

## Specifications

  - Version: v0.6.2 of mod, ModTheSpire 2.7, 06-21-2018 main branch
  - Platform: Windows 8.1 x64
  - Subsystem:

**Comment by Moocowsgomoo** [comment]
Fixed in latest release v0.6.3. Was checking for "Weak" when the actual power ID is "Weakened".

**Comment by KongMD-Steam** [comment]
Great! I can pick this card again :+1:
