### ISSUE TITLE
Heavy Framerate Lag/Stuttering with the construct in Borderless Fullscreen

### ISSUE THREAD

**Issue by CrabBucket** [Moocowsgomoo/StS-ConstructMod#8]
I have a gtx 1080 with a 3.9ghz processor.

I get pretty bad framerate stuttering when playing the character in Borderless Fullscreen.  It was fixed upon changing to Fullscreen.  Only mods installed is base mod + The Construct.  Have not tried any other custom characters besides The Construct so it could be something weird on my end.

**Comment by CrabBucket** [comment]
Originally thought that going fullscreen would fixed the issue but that is not the case.  After finishing the first fight it stuttered a bit pulling up rewards and then the consequent fights were also somewhat stuttery, better then borderless but it did not fix the issue.

**Comment by CrabBucket** [comment]
Went to regular windowed mode and it fixed the stuttering.  I tried V-sync on/off did nothing. Switched to the beta branch did nothing. Did not check if going back to the normal release of the game and windowed is fine or if I need both beta branch and windowed mode.

**Comment by Moocowsgomoo** [comment]
Definitely try with other character mods if you get the chance - I don't think the construct does anything special with rendering that's not handled by BaseMod. Two other questions that might help:
 - Did you have any mega-upgraded cards / did mega-upgraded cards seem to cause more stutter?
 - If you Alt+Tab to the log in borderless fullscreen, is it spamming any messages or posting at a normal rate?

**Comment by CrabBucket** [comment]
I get the issue with all custom characters.  Weird.
